name: React Native Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    env:
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        if: success()

      - name: Install npm dependencies
        run: npm install

      - name: Install Java (for Android build)
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "zulu"

      - name: Install CocoaPods (for iOS build)
        run: sudo gem install cocoapods

      - name: Make gradlew executable (for Android build)
        run: chmod +x ./android/gradlew

      - name: Bundle RN Android assets
        run: npx react-native bundle --platform android --dev false --entry-file Main.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Clean up Android resources
        run: rm -rf ./android/app/src/main/res/drawable-* && rm -rf ./android/app/src/main/res/raw

      - name: Build Android APK
        run: cd ./android && ./gradlew clean app:assembleRelease -x bundleReleaseJsAndAssets

      - name: Archive iOS build
        run: |
          cd ios && pod install && xcodebuild archive -workspace FoodApp.xcworkspace -scheme FoodApp -archivePath FoodApp.xcarchive

      - name: Export iOS IPA
        run: |
          xcodebuild -exportArchive -archivePath FoodApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ./

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-app-release.ipa
          path: FoodApp.ipa
